// Generated by Ludicord. Changes will be replaced by ludicord dev or ludicord build.
import "ludicord/navigation";

declare module "ludicord/navigation" {
  interface LudicordRouteRegistry {
    readonly prefix: "/" | "/privacy" | "/terms";
    readonly pagePattern: "/" | "/privacy" | "/terms";
    readonly pageParams: {
      readonly "/": Readonly<Record<string, never>>;
      readonly "/privacy": Readonly<Record<string, never>>;
      readonly "/terms": Readonly<Record<string, never>>;
    };
    readonly embed: "home" | "me";
    readonly embedPattern: "home" | "me";
    readonly embedsByPrefix: {
      readonly "/": "home" | "me";
      readonly "/privacy": never;
      readonly "/terms": never;
    };
    readonly api: `/api/export/${string}` | "/api/export" | "/api/health";
    readonly websocket: "/ws/board";
    readonly embedParams: {
      readonly "home": Readonly<Record<string, never>>;
      readonly "me": Readonly<Record<string, never>>;
    };
    readonly apiParams: {
      readonly "/api/export/:token": { readonly "token": string };
      readonly "/api/export": Readonly<Record<string, never>>;
      readonly "/api/health": Readonly<Record<string, never>>;
    };
    readonly websocketParams: {
      readonly "/ws/board": Readonly<Record<string, never>>;
    };
    readonly config: {
      readonly defaultEmbed: "home";
      readonly outsideDiscord: "allow";
      readonly authRequired: true;
      readonly strictMode: true;
      readonly clientAssetWarningLimit: 512000;
    };
  }
}
